$site_gnats_host = 'localhost';
$site_gnats_port = '1529';
$site_mail_domain = '@plt-scheme.org';
$scrolling_menu_default_size = 8;
$no_create_without_access = 'edit';
%site_pr_submission_address = ('default' => 'bugs@plt-scheme.org');
$site_banner_text = 'PLT Bugs';
$site_banner_background = '#000000';
$site_banner_foreground = '#ffff20';
$site_button_background = '#404040';
$site_button_foreground = '#a0ffa0';
$site_background = '#ffc0ff';
$edit_url = 'https://internal.plt-scheme.org/bugs/';
